// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALsavxnjeHQAjs4AYGGdd7OiRSbg5Z2D4',
    appId: '1:497472759859:web:25f582c0a1cdc69c7e1b46',
    messagingSenderId: '497472759859',
    projectId: 'pokerapp-6602c',
    authDomain: 'pokerapp-6602c.firebaseapp.com',
    storageBucket: 'pokerapp-6602c.appspot.com',
    measurementId: 'G-TC0QZ836QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGJg6TA-3qYqIl9GHn26fmMXwoHydC9o',
    appId: '1:497472759859:android:f1544248aca5caee7e1b46',
    messagingSenderId: '497472759859',
    projectId: 'pokerapp-6602c',
    storageBucket: 'pokerapp-6602c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQDBjG0O1A-17TVW_s7SNygsixhh1OrQ',
    appId: '1:497472759859:ios:b6dbe479e57550287e1b46',
    messagingSenderId: '497472759859',
    projectId: 'pokerapp-6602c',
    storageBucket: 'pokerapp-6602c.appspot.com',
    iosClientId: '497472759859-k26ft39b530ntkiuf3d4i4gf4g430qvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQDBjG0O1A-17TVW_s7SNygsixhh1OrQ',
    appId: '1:497472759859:ios:4ca9784cac624c457e1b46',
    messagingSenderId: '497472759859',
    projectId: 'pokerapp-6602c',
    storageBucket: 'pokerapp-6602c.appspot.com',
    iosClientId: '497472759859-jeaqgfjajr4l57nbueuauu9v9ccfsear.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokerApp.RunnerTests',
  );
}
